trigger:
 batch: true
 branches:
    include:
    - master
pool:
  name: Hosted VS2017
  demands:
  - msbuild
  - visualstudio
stages:
- stage: Build
  jobs:     
  - job: VSBuild
    steps:
    - task: VSBuild@1
      displayName: 'Build solution **\*.sln'
      inputs:
        solution: '**\*.sln'
        platform: '$(BuildPlatform)'
        configuration: '$(BuildConfiguration)'